"use client";

import { useMemo, useState } from "react";
import { CalendarDays, ReceiptText, WalletCards } from "lucide-react";
import { PageHeader } from "@/components/shared/PageHeader";
import { EmptyState, ErrorState, LoadingState } from "@/components/shared/States";
import { RevenueChart } from "@/features/dashboard/RevenueChart";
import { useSupabaseData } from "@/features/data/SupabaseDataProvider";
import { formatDateTime } from "@/lib/format/date";
import { formatMoney } from "@/lib/format/money";

type Period = "week" | "month";
function startOfDay(date: Date) { return new Date(date.getFullYear(), date.getMonth(), date.getDate()); }
function isInRange(value: string, start: Date, end: Date) { const date = new Date(value); return date >= start && date < end; }
export default function RevenuePage() {
  const { rentals, loading, error } = useSupabaseData(); const [period, setPeriod] = useState<Period>("week");
  const { completed, total, series, previousTotal } = useMemo(() => { const today = startOfDay(new Date()); const start = period === "week" ? new Date(today.getFullYear(), today.getMonth(), today.getDate() - ((today.getDay() + 6) % 7)) : new Date(today.getFullYear(), today.getMonth(), 1); const end = period === "week" ? new Date(start.getFullYear(), start.getMonth(), start.getDate() + 7) : new Date(today.getFullYear(), today.getMonth() + 1, 1); const span = end.getTime() - start.getTime(); const previousStart = new Date(start.getTime() - span); const completed = rentals.filter((rental) => rental.status === "RETURNED" && isInRange(rental.end_time, start, end)); const total = completed.reduce((sum, rental) => sum + rental.rental_price, 0); const previousTotal = rentals.filter((rental) => rental.status === "RETURNED" && isInRange(rental.end_time, previousStart, start)).reduce((sum, rental) => sum + rental.rental_price, 0); const series = period === "week" ? Array.from({ length: 7 }, (_, index) => { const day = new Date(start); day.setDate(start.getDate() + index); const next = new Date(day); next.setDate(day.getDate() + 1); return { label: index === 6 ? "CN" : `T${index + 2}`, amount: completed.filter((rental) => isInRange(rental.end_time, day, next)).reduce((sum, rental) => sum + rental.rental_price, 0), tooltip: new Intl.DateTimeFormat("vi-VN", { day: "2-digit", month: "2-digit" }).format(day) }; }) : Array.from({ length: 5 }, (_, index) => { const from = new Date(start); from.setDate(1 + index * 7); const to = new Date(start); to.setDate(1 + (index + 1) * 7); return { label: `Tuần ${index + 1}`, amount: completed.filter((rental) => isInRange(rental.end_time, from, to)).reduce((sum, rental) => sum + rental.rental_price, 0), tooltip: `Tuần ${index + 1}` }; }); return { completed, total, series, previousTotal }; }, [period, rentals]);
  const cameraCount = new Set(completed.map((rental) => rental.camera_id)).size; const trend = previousTotal > 0 ? Math.round(((total - previousTotal) / previousTotal) * 100) : null;
  return <><PageHeader title="Doanh thu" description="Chỉ tính đơn đã hoàn thành và trả máy." />{error ? <ErrorState message={error} /> : loading ? <LoadingState /> : <><div className="mb-4 inline-flex rounded-xl bg-[#FFF0F5] p-1"><button type="button" onClick={() => setPeriod("week")} className={`min-h-9 rounded-lg px-4 text-sm font-semibold ${period === "week" ? "bg-white text-pine-dark shadow-sm" : "text-[#7A6C76]"}`}>Tuần</button><button type="button" onClick={() => setPeriod("month")} className={`min-h-9 rounded-lg px-4 text-sm font-semibold ${period === "month" ? "bg-white text-pine-dark shadow-sm" : "text-[#7A6C76]"}`}>Tháng</button></div><section className="rounded-2xl bg-[#D95786] p-5 text-white shadow-[0_12px_28px_rgba(185,67,112,0.22)]"><div className="flex items-start justify-between"><div><p className="text-sm text-white/80">Tổng doanh thu {period === "week" ? "tuần này" : "tháng này"}</p><p className="mt-2 text-3xl font-bold">{formatMoney(total)}</p>{trend !== null ? <p className="mt-2 text-sm text-white/85">{trend >= 0 ? "+" : ""}{trend}% so với kỳ trước</p> : null}</div><div className="rounded-xl bg-white/15 p-3"><WalletCards size={23} /></div></div></section><div className="mt-4 grid grid-cols-2 gap-3"><Stat icon={<ReceiptText size={18} />} label="Đơn hoàn thành" value={completed.length} /><Stat icon={<CalendarDays size={18} />} label="Máy đã được thuê" value={cameraCount} /></div><div className="mt-4"><RevenueChart title={`Doanh thu theo ${period === "week" ? "ngày" : "tuần"}`} subtitle="Chạm vào cột để xem giá trị" items={series} /></div><section className="mt-5">{completed.length ? <div className="space-y-3">{completed.map((rental) => <article key={rental.id} className="app-card flex items-start justify-between gap-4 p-4"><div className="min-w-0"><p className="font-bold text-ink">{rental.customer_name}</p><p className="mt-1 truncate text-sm text-[#7A6C76]">{rental.camera?.name} · {formatDateTime(rental.end_time)}</p></div><p className="shrink-0 font-bold text-pine-dark">{formatMoney(rental.rental_price)}</p></article>)}</div> : <EmptyState title="Chưa có doanh thu trong kỳ này." />}</section></>}</>;
}
function Stat({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) { return <article className="app-card p-4"><div className="mb-2 inline-flex rounded-lg bg-[#FFF1F6] p-2 text-pine-dark">{icon}</div><p className="text-xs text-[#7A6C76]">{label}</p><p className="mt-1 text-xl font-bold text-ink">{value}</p></article>; }