"use client";

import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";
import { Button } from "@/components/shared/Button";
import { ErrorState } from "@/components/shared/States";
import { findRentalOverlaps, listCameras, saveRental, validateRentalInput } from "@/features/data/localStore";
import { formatDateTime, toDateTimeLocalValue } from "@/lib/format/date";
import { RENTAL_STATUS_LABELS, type RentalFormInput, type RentalWithCamera } from "@/types/domain";

const blankInput: RentalFormInput = { camera_id: "", customer_name: "", customer_phone: "", customer_address: "", start_time: "", end_time: "", rental_price: "0", deposit_info: "", status: "BOOKED", note: "" };

export function RentalForm({ rental }: { rental?: RentalWithCamera | null }) {
  const router = useRouter();
  const cameras = useMemo(() => listCameras().filter((camera) => camera.status !== "INACTIVE"), []);
  const [errors, setErrors] = useState<string[]>([]);
  const [overlaps, setOverlaps] = useState<RentalWithCamera[]>([]);
  const [input, setInput] = useState<RentalFormInput>(() => rental ? { camera_id: rental.camera_id, customer_name: rental.customer_name, customer_phone: rental.customer_phone ?? "", customer_address: rental.customer_address ?? "", start_time: toDateTimeLocalValue(rental.start_time), end_time: toDateTimeLocalValue(rental.end_time), rental_price: String(rental.rental_price), deposit_info: rental.deposit_info ?? "", status: rental.status, note: rental.note ?? "" } : blankInput);
  function update<K extends keyof RentalFormInput>(key: K, value: RentalFormInput[K]) { setInput((current) => ({ ...current, [key]: value })); setErrors([]); setOverlaps([]); }
  function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const validationErrors = validateRentalInput(input); if (validationErrors.length > 0) { setErrors(validationErrors); return; } const overlapItems = findRentalOverlaps(input, rental?.id); if (overlapItems.length > 0) { setOverlaps(overlapItems); setErrors([`${overlapItems[0].camera?.name ?? "Máy ảnh"} đã có lịch thuê trong khoảng thời gian này.`]); return; } const saved = saveRental(input, rental?.id); window.alert(rental ? "Đã cập nhật lịch thuê." : "Đã tạo lịch thuê."); router.push(saved ? `/rentals/${saved.id}` : "/rentals"); router.refresh(); }
  return <form onSubmit={submit} className="app-panel space-y-0 p-4">{errors.length > 0 ? <ErrorState message={errors.join(" ")} /> : null}{overlaps.length > 0 ? <div className="rounded-2xl border border-[#F6D7B6] bg-[#FFF8E9] p-4 text-sm text-[#875012]"><div className="font-semibold">Lịch đang bị trùng</div><div className="mt-2 space-y-1">{overlaps.map((item) => <p key={item.id}>{item.customer_name} · {formatDateTime(item.start_time)} → {formatDateTime(item.end_time)}</p>)}</div></div> : null}<Section title="Khách hàng"><Field label="Tên khách *"><input value={input.customer_name} onChange={(event) => update("customer_name", event.target.value)} className="input" /></Field><Field label="Số điện thoại"><input inputMode="tel" value={input.customer_phone} onChange={(event) => update("customer_phone", event.target.value)} className="input" /></Field><Field label="Địa chỉ" className="sm:col-span-2"><input value={input.customer_address} onChange={(event) => update("customer_address", event.target.value)} className="input" /></Field></Section><Section title="Máy thuê"><Field label="Chọn máy *"><select value={input.camera_id} onChange={(event) => update("camera_id", event.target.value)} className="input"><option value="">Chọn máy ảnh</option>{cameras.map((camera) => <option key={camera.id} value={camera.id}>{camera.name}</option>)}</select></Field></Section><Section title="Thời gian"><Field label="Ngày giờ nhận *"><input type="datetime-local" value={input.start_time} onChange={(event) => update("start_time", event.target.value)} className="input" /></Field><Field label="Ngày giờ trả *"><input type="datetime-local" value={input.end_time} onChange={(event) => update("end_time", event.target.value)} className="input" /></Field></Section><Section title="Chi phí"><Field label="Tiền thuê *"><input inputMode="numeric" value={input.rental_price} onChange={(event) => update("rental_price", event.target.value)} className="input" /></Field><Field label="Thông tin cọc"><input value={input.deposit_info} onChange={(event) => update("deposit_info", event.target.value)} className="input" /></Field></Section><Section title="Khác"><Field label="Ghi chú"><textarea value={input.note} onChange={(event) => update("note", event.target.value)} className="input min-h-24" /></Field><Field label="Trạng thái"><select value={input.status} onChange={(event) => update("status", event.target.value as RentalFormInput["status"])} className="input">{Object.entries(RENTAL_STATUS_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field></Section><Button className="mt-4 w-full" type="submit">Lưu đơn</Button></form>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="border-t border-[#F3E3E9] py-4 first:border-t-0 first:pt-0"><h2 className="mb-4 text-base font-bold text-ink">{title}</h2><div className="grid gap-4 sm:grid-cols-2">{children}</div></section>; }
function Field({ label, children, className = "" }: { label: string; children: React.ReactNode; className?: string }) { return <label className={`block ${className}`}><span className="mb-1.5 block text-sm font-medium text-[#514650]">{label}</span>{children}</label>; }