"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useState } from "react";
import { CheckCircle2, X } from "lucide-react";
import { Button } from "@/components/shared/Button";
import { ConfirmButton } from "@/components/shared/ConfirmButton";
import { PageHeader } from "@/components/shared/PageHeader";
import { EmptyState } from "@/components/shared/States";
import { RentalStatusBadge } from "@/components/shared/StatusBadges";
import { deleteRental, getRental, updateRentalStatus } from "@/features/data/localStore";
import { formatDateTime } from "@/lib/format/date";
import { formatMoney } from "@/lib/format/money";

export default function RentalDetailPage() {
  const params = useParams<{ id: string }>(); const router = useRouter(); const [returnSheet, setReturnSheet] = useState(false); const [returnNote, setReturnNote] = useState(""); const rental = getRental(params.id);
  if (!rental) return <EmptyState title="Không tìm thấy đơn thuê." />;
  const changeStatus = (status: typeof rental.status) => { updateRentalStatus(rental.id, status); router.refresh(); };
  const finishReturn = () => { updateRentalStatus(rental.id, "RETURNED", returnNote); setReturnSheet(false); router.refresh(); };
  return <><PageHeader title="Chi tiết lịch thuê" description={rental.customer_name} /><section className="app-panel overflow-hidden"><div className="border-b border-[#F4E4EA] p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="text-xl font-bold text-ink">{rental.camera?.name ?? "Máy ảnh"}</h2><p className="mt-1 text-sm text-[#7A6C76]">{rental.customer_name} · {rental.customer_phone ?? "Chưa có số điện thoại"}</p></div><RentalStatusBadge status={rental.status} /></div></div><div className="p-4"><dl className="grid gap-4 sm:grid-cols-2"><Info label="Khách hàng" value={rental.customer_name} /><Info label="Địa chỉ" value={rental.customer_address ?? "Chưa ghi nhận"} /><Info label="Nhận máy" value={formatDateTime(rental.start_time)} /><Info label="Trả máy" value={formatDateTime(rental.end_time)} /><Info label="Giá thuê" value={formatMoney(rental.rental_price)} /><Info label="Tiền cọc" value={rental.deposit_info ?? "Chưa ghi nhận"} /><Info label="Tổng tiền" value={formatMoney(rental.rental_price)} /><Info label="Ghi chú" value={rental.note ?? "Không có"} /></dl><div className="mt-6 flex flex-col gap-2 sm:flex-row sm:flex-wrap"><Link href={`/rentals/${rental.id}/edit`} className="touch-target inline-flex items-center justify-center rounded-xl border border-line px-4 text-sm font-semibold text-ink">Sửa lịch</Link>{rental.status === "BOOKED" ? <Button type="button" onClick={() => changeStatus("RENTING")} className="bg-amber hover:bg-[#C48225]">Nhận máy</Button> : null}{rental.status === "RENTING" ? <Button type="button" onClick={() => setReturnSheet(true)}><CheckCircle2 className="mr-2" size={18} />Trả máy</Button> : null}{(rental.status === "BOOKED" || rental.status === "RENTING") ? <Button type="button" variant="secondary" onClick={() => changeStatus("CANCELLED")}>Hủy đơn</Button> : null}<ConfirmButton message="Bạn có chắc muốn xóa lịch thuê này?" onConfirm={() => { deleteRental(rental.id); router.push("/history"); }} className="touch-target rounded-xl bg-rose px-4 text-sm font-semibold text-white">Xóa</ConfirmButton></div></div></section>{returnSheet ? <ReturnSheet value={returnNote} onChange={setReturnNote} onClose={() => setReturnSheet(false)} onSubmit={finishReturn} /> : null}</>;
}
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-medium uppercase tracking-wide text-[#8A7B84]">{label}</dt><dd className="mt-1 text-sm font-semibold leading-5 text-ink">{value}</dd></div>; }
function ReturnSheet({ value, onChange, onClose, onSubmit }: { value: string; onChange: (value: string) => void; onClose: () => void; onSubmit: () => void }) { const options = ["Máy bình thường", "Có vết xước", "Thiếu phụ kiện", "Trả muộn"]; return <div className="fixed inset-0 z-30 flex items-end bg-[#2B2330]/35" role="dialog" aria-modal="true" aria-label="Xác nhận trả máy" onMouseDown={onClose}><section className="safe-bottom w-full rounded-t-2xl bg-white p-5 shadow-2xl" onMouseDown={(event) => event.stopPropagation()}><div className="mx-auto mb-4 h-1.5 w-10 rounded-full bg-[#E7D4DD]" /><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-bold text-ink">Xác nhận trả máy</h2><p className="mt-1 text-sm text-[#7A6C76]">Lưu lại tình trạng máy để xem trong lịch sử.</p></div><button type="button" onClick={onClose} className="flex h-10 w-10 items-center justify-center rounded-xl text-[#7A6C76]" aria-label="Đóng"><X size={20} /></button></div><div className="mt-4 flex flex-wrap gap-2">{options.map((option) => <button key={option} type="button" onClick={() => onChange(option)} className={`min-h-9 rounded-full px-3 text-sm font-semibold ${value === option ? "bg-[#FFF0F5] text-pine-dark" : "border border-line text-[#665963]"}`}>{option}</button>)}</div><label className="mt-4 block"><span className="app-field-label">Ghi chú khác</span><textarea value={value} onChange={(event) => onChange(event.target.value)} className="input min-h-24" placeholder="Ví dụ: máy sạch, đủ pin và phụ kiện" /></label><Button type="button" onClick={onSubmit} className="mt-5 w-full">Hoàn tất trả máy</Button></section></div>; }